version: "3.2"
services:
  server:
    build:
      context: "."
      dockerfile: "server/Dockerfile"
    restart: always
    ports:
      - 4433:4433
    volumes:
      - ./distances:/server/distances
  nginx:
    build:
      context: "./nginx/"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.cert:/etc/letsencrypt
    depends_on:
      - server
