import { SongName } from "tunescape07-shared";

const easy = "easy";
const normal = "normal";
const hard = "hard";

export const songDurations: Record<SongName, "easy" | "normal" | "hard" | number> = {
  "7th Realm": hard,
  Adventure: easy,
  "Al Kharid": easy,
  "Alchemical Attack!": normal,
  "All's Fairy in Love & War": hard,
  Alone: normal,
  "Altar Ego": normal,
  "Alternative Root": hard,
  "Amascut's Promise": easy,
  "Ambient Jungle": normal,
  "The Ancient Prison": normal,
  "The Angel's Fury": normal,
  Anywhere: normal,
  "Ape-ex Predator": easy,
  Arabian: easy,
  "Arabian 2": normal,
  "Arabian 3": normal,
  Arabique: hard,
  "Arachnids of Vampyrium": easy,
  Arboretum: hard,
  Arcane: normal,
  "Architects of Prifddinas": easy,
  "Armadyl Alliance": easy,
  Armageddon: easy,
  "Army of Darkness": normal,
  Arrival: normal,
  Artistry: hard,
  Ascent: easy,
  "Assault and Battery": normal,
  "Attack 1": easy,
  "Attack 2": hard,
  "Attack 3": hard,
  "Attack 4": easy,
  "Attack 5": normal,
  "Attack 6": hard,
  Attention: normal,
  "Autumn Voyage": easy,
  "Awful Anthem": hard,
  "Aye Car Rum Ba": hard,
  Aztec: hard,
  "Back to Life": normal,
  Background: normal,
  Bait: hard,
  "Ballad of Enchantment": easy,
  "Ballad of the Basilisk": hard,
  "Bandit Camp": normal,
  "Bandos Battalion": easy,
  Bane: normal,
  "The Bane of Ashihama": easy,
  "Barb Wire": hard,
  "Barbarian Workout": normal,
  Barbarianism: easy,
  "Barking Mad": hard,
  Baroque: normal,
  "Barren Land": hard,
  "Beetle Juice": hard,
  "Beneath Cursed Sands": easy,
  "Beneath the Kingdom": normal,
  "Beneath the Stronghold": normal,
  Beyond: hard,
  "Beyond the Meadow": normal,
  "Big Chords": normal,
  "Blistering Barnacles": hard,
  "Blood Rush": easy,
  Bloodbath: normal,
  "Bob's on Holiday": hard,
  "Body Parts": hard,
  "Bolrie's Diary": hard,
  "Bone Dance": hard,
  "Bone Dry": hard,
  "Book of Spells": normal,
  Borderland: normal,
  "Box of Delights": easy,
  "Brain Battle": hard,
  Breeze: normal,
  "Brew Hoo Hoo!": hard,
  "Brimstail's Scales": hard,
  "Bubble and Squeak": hard,
  "Bunny's Sugar Rush": normal,
  "Burning Desire": hard,
  "The Burning Sun": hard,
  "Cabin Fever": hard,
  "Cain's Tutorial": normal,
  Camelot: normal,
  "Castle Wars": normal,
  "Catacombs and Tombs": hard,
  "Catch Me If You Can": hard,
  "Cave Background": hard,
  "Cave of Beasts": hard,
  "Cave of the Goblins": hard,
  Cavern: hard,
  "The Cellar Dwellers": hard,
  "Cellar Song": hard,
  "Chain of Command": hard,
  Chamber: hard,
  "Chef Surprise": normal,
  "Chickened Out": hard,
  "Children of the Sun": hard,
  "Chompy Hunt": normal,
  "The Chosen": hard,
  "City of the Dead": normal,
  "Clan Wars": hard,
  Clanliness: normal,
  Claustrophobia: hard,
  "Close Quarters": normal,
  Coil: easy,
  "Colossus of the Deep": normal,
  Competition: hard,
  Complication: hard,
  Confrontation: hard,
  "The Consortium": hard,
  Conspiracy: hard,
  Contest: normal,
  "Corporal Punishment": hard,
  "Corridors of Power": hard,
  "Country Jig": easy,
  Courage: hard,
  "Creature Cruelty": hard,
  "Creeping Vines": normal,
  "Crest of a Wave": hard,
  "Crystal Castle": normal,
  "Crystal Cave": hard,
  "Crystal Sword": normal,
  Cursed: hard,
  "The Curtain Closes": easy,
  "Dagannoth Dawn": hard,
  "Dance of Death": normal,
  "Dance of the Meilyr": easy,
  "Dance of the Nylocas": easy,
  "Dance of the Undead": easy,
  Dangerous: normal,
  "A Dangerous Game": hard,
  "Dangerous Road": hard,
  "Dangerous Way": normal,
  Dark: normal,
  "The Dark Beast Sotetseg": easy,
  "Darkly Altared": easy,
  Darkmeyer: normal,
  "Darkness in the Depths": hard,
  "Davy Jones' Locker": normal,
  "Dead Can Dance": normal,
  "Dead Quiet": normal,
  Deadlands: normal,
  "Deep Down": hard,
  "Deep Wildy": normal,
  Delrith: normal,
  "The Depths": hard,
  "Desert Heat": normal,
  "Desert Voyage": normal,
  "The Desert": normal,
  "The Desolate Isle": easy,
  "The Desolate Mage": easy,
  "Devils May Care": normal,
  "Diango's Little Helpers": hard,
  "Dies Irae": hard,
  "Dimension X": hard,
  "Distant Land": normal,
  "Distillery Hilarity": normal,
  "Dogs of War": normal,
  Dogfight: hard,
  "Domain of the Vampyres": normal,
  "Don't Panic Zanik": hard,
  "The Doors of Dinh": easy,
  Doorways: easy,
  "Dorgeshuun City": hard,
  "Dorgeshuun Deep": hard,
  "Dorgeshuun Treaty": hard,
  "Dot's Yuletide": hard,
  "Down and Out": hard,
  "Down Below": normal,
  "Down by the Docks": normal,
  "Down to Earth": normal,
  "The Dragon Slayer": hard,
  "Dragontooth Island": normal,
  Dream: easy,
  Dreamstate: hard,
  "The Emir's Arena": normal,
  "Dunes of Eternity": easy,
  Dunjun: hard,
  "Dusk in Yu'biusk": hard,
  "Dwarf Theme": easy,
  "Dwarven Domain": normal,
  Dynasty: normal,
  "Eagles' Peak": normal,
  "Easter Jig": hard,
  Egypt: normal,
  "Elven Guardians": easy,
  "Elven Mist": normal,
  "Elven Seed": normal,
  Emotion: normal,
  Emperor: normal,
  "The Enchanter": normal,
  "The Enclave": easy,
  Escape: hard,
  Espionage: easy,
  Etceteria: normal,
  "Eve's Epinette": hard,
  Everlasting: normal,
  "Everlasting Fire": easy,
  "The Everlasting Slumber": normal,
  Everywhere: normal,
  "Evil Bob's Island": hard,
  Expanse: easy,
  Expecting: normal,
  Expedition: hard,
  Exposed: normal,
  "Eye See You": easy,
  "Eye of the Storm": normal,
  Faerie: normal,
  "The Fairy Dragon": hard,
  "Faith of the Hefin": easy,
  Faithless: normal,
  "The Fallen Empire": normal,
  Fanfare: easy,
  "Fanfare 2": normal,
  "Fanfare 3": normal,
  "Fangs for the Memory": hard,
  "Far Away": normal,
  "The Far Side": hard,
  "A Farmer's Grind": easy,
  "The Fat Lady Sings": easy,
  "Fe Fi Fo Fum": hard,
  "Fear and Loathing": hard,
  "Fenkenstrain's Refrain": normal,
  "A Festive Party": hard,
  "Fight of the Basilisk": hard,
  "Fight or Flight": hard,
  "Find My Way": hard,
  "Fire and Brimstone": normal,
  "Fire in the Deep": easy,
  "The Fires of Lletya": normal,
  Fishing: normal,
  "Floating Free": hard,
  "Flute Salad": easy,
  "Food for Thought": normal,
  Forbidden: normal,
  Forest: normal,
  "The Forests of Shayzien": normal,
  Forever: normal,
  "Forgettable Melody": hard,
  Forgotten: hard,
  "A Forgotten Religion": hard,
  "The Forgotten Tomb": hard,
  "The Forlorn Homestead": easy,
  "The Forsaken Tower": hard,
  "The Forsaken": hard,
  Fossilised: hard,
  "The Foundry": hard,
  "The Fragment": hard,
  "The Fremennik Kings": hard,
  Frogland: hard,
  Frostbite: normal,
  "Fruits de Mer": normal,
  "Ful to the Brim": hard,
  "Funny Bunnies": normal,
  "The Galleon": hard,
  Gaol: normal,
  Garden: easy,
  "Garden of Autumn": hard,
  "Garden of Spring": hard,
  "Garden of Summer": hard,
  "Garden of Winter": hard,
  "The Gates of Menaphos": hard,
  "The Gauntlet": easy,
  "The Genie": hard,
  "Getting Down to Business": easy,
  "Gill Bill": normal,
  "Gnome King": easy,
  "Gnome Village": easy,
  "Gnome Village 2": normal,
  "Gnome Village Party": hard,
  Gnomeball: easy,
  "Goblin Game": hard,
  "Goblin Village": easy,
  "Golden Touch": hard,
  "The Golem": normal,
  Greatness: normal,
  "Grimly Fiendish": hard,
  "Grip of the Talon": hard,
  Grotto: hard,
  "Grow Grow Grow": easy,
  Grumpy: normal,
  "Guardians of the Rift": easy,
  "The Guardians Prepare": easy,
  "H.A.M. and Seek": hard,
  "H.A.M. Attack": hard,
  "H.A.M. Fisted": hard,
  Harmony: easy,
  "Harmony 2": hard,
  "Haunted Mine": hard,
  "Have a Blast": normal,
  "Have an Ice Day": normal,
  "Head to Head": hard,
  "Healin' Feelin'": hard,
  "Heart and Mind": hard,
  "Hells Bells": normal,
  Hermit: hard,
  "High Seas": normal,
  "High Spirits": hard,
  "His Faithful Servants": normal,
  "Hoe Down": easy,
  "Home Sweet Home": easy,
  Horizon: normal,
  "The Houses of Kourend": hard,
  Hypnotised: hard,
  Iban: hard,
  "Ice and Fire": easy,
  "Ice Melody": normal,
  Illusive: hard,
  Impetuous: normal,
  Impulses: normal,
  "In Between": hard,
  "In the Brine": normal,
  "In the Clink": normal,
  "In the Manor": normal,
  "In the Pits": easy,
  "In the Shadows": normal,
  Inadequacy: hard,
  Incantation: hard,
  Inferno: easy,
  "Insect Queen": normal,
  Inspiration: normal,
  "Into the Abyss": hard,
  "Into the Tombs": easy,
  Intrepid: hard,
  Invader: normal,
  "Iorwerth's Lament": normal,
  "Island Life": normal,
  "Island of the Trolls": normal,
  "Isle of Everywhere": normal,
  "It's not over 'til...": easy,
  "Itsy Bitsy...": hard,
  "Jaws of the Basilisk": hard,
  "Jaws of Gluttony": hard,
  "Jester Minute": hard,
  "Jolly R": normal,
  "Joy of the Hunt": normal,
  "Judgement of the Depths": hard,
  "Jungle Bells": hard,
  "Jungle Hunt": normal,
  "Jungle Island": normal,
  "Jungle Island Xmas": hard,
  "Jungle Troubles": normal,
  "Jungly 1": normal,
  "Jungly 2": easy,
  "Jungly 3": normal,
  "Kanon of Kahlith": hard,
  "Karamja Jam": hard,
  "King of the Trolls": hard,
  Kingdom: normal,
  Knightly: easy,
  Knightmare: hard,
  "Kourend the Magnificent": easy,
  "La Mort": hard,
  Labyrinth: hard,
  Lagoon: normal,
  "Laid to Rest": easy,
  Lair: hard,
  "Lair of the Basilisk": hard,
  Lament: hard,
  "Lament for the Hallowed": normal,
  "Lament of Meiyerditch": normal,
  "Land Down Under": hard,
  "Land of Snow": normal,
  "Land of the Dwarves": hard,
  Landlubber: normal,
  "Last King of the Yarasa": easy,
  "Last Man Standing": hard,
  "The Last Shanty": normal,
  "Last Stand": hard,
  Lasting: easy,
  "Lava is Mine": normal,
  Legend: normal,
  Legion: normal,
  "Life's a Beach!": normal,
  Lighthouse: normal,
  Lightness: normal,
  Lightwalk: normal,
  "Little Cave of Horrors": hard,
  Lonesome: hard,
  "Long Ago": normal,
  "Long Way Home": easy,
  "The Longramble Scramble": normal,
  "Look to the Stars": hard,
  "Looking Back": normal,
  "Lore and Order": hard,
  "The Lost Melody": hard,
  "Lost Soul": normal,
  "The Lost Tribe": hard,
  "Lower Depths": easy,
  "Lucid Dream": hard,
  "Lucid Nightmare": hard,
  Lullaby: normal,
  Lumbering: normal,
  "The Lunar Isle": normal,
  "Mad Eadgar": hard,
  "The Mad Mole": normal,
  "Mage Arena": normal,
  "Magic Dance": normal,
  "Magic Magic Magic": normal,
  "Magical Journey": normal,
  "The Maiden's Anger": easy,
  "The Maiden's Sorrow": easy,
  "Major Miner": hard,
  "Making Waves": normal,
  Malady: normal,
  March: normal,
  "March of the Shayzien": easy,
  Marooned: normal,
  Marzipan: hard,
  Masquerade: hard,
  "Master of Puppets": normal,
  Mastermindless: hard,
  Mausoleum: hard,
  "Maws Jaws & Claws": easy,
  "The Maze": hard,
  "Meddling Kids": hard,
  Medieval: easy,
  Mellow: normal,
  Melodrama: normal,
  Meridian: normal,
  "Method of Madness": hard,
  "Miles Away": normal,
  "Military Life": normal,
  "The Militia": easy,
  "Mind over Matter": hard,
  "Miracle Dance": hard,
  Mirage: hard,
  Miscellania: easy,
  "The Mollusc Menace": normal,
  "Monarch Waltz": normal,
  "Monkey Badness": hard,
  "Monkey Business": normal,
  "Monkey Madness": normal,
  "Monkey Sadness": hard,
  "Monkey Trouble": hard,
  "Monster Melee": hard,
  "The Monsters Below": hard,
  Moody: normal,
  "Mor Ul Rek": normal,
  "More Than Meets the Eye": easy,
  Morytania: normal,
  "Morytanian Mystery": hard,
  "A Mother's Curse": easy,
  "Mother Ruckus": hard,
  "Mouse Trap": normal,
  "Mudskipper Melody": easy,
  "Museum Medley": normal,
  "Mutant Medley": hard,
  "My Arm's Journey": hard,
  "Mystics of Nature": easy,
  Mythical: normal,
  "Narnode's Theme": hard,
  Natural: normal,
  "The Navigator": hard,
  "Nether Realm": hard,
  Neverland: normal,
  "Newbie Farming": normal,
  "Newbie Melody": easy,
  "Night of the Vampyre": normal,
  Nightfall: normal,
  "The Nightmare Continues": easy,
  "No Pasaran": normal,
  "No Way Out": hard,
  "The Noble Rodent": hard,
  Nomad: normal,
  "Norse Code": normal,
  "Not a Moment of Relief": normal,
  "Nox Irae": hard,
  "Null and Void": normal,
  "Ogre the Top": hard,
  "Oh Rats!": normal,
  "The Old Ones": hard,
  "On the Frontline": normal,
  "On the Shore": normal,
  "On the Up": hard,
  "On the Wing": normal,
  "On Thin Ice": easy,
  "Oncoming Foe": hard,
  "Organ Music 1": hard,
  "Organ Music 2": hard,
  Oriental: hard,
  "The Other Side": normal,
  "Out at the Mines": normal,
  "Out of the Deep": normal,
  "Over to Nardah": normal,
  Overpass: normal,
  Overture: normal,
  Parade: normal,
  "The Part Where You Die": normal,
  "Path of Peril": hard,
  "The Penguin Bards": normal,
  "Penguin Plots": normal,
  Pathways: hard,
  "Pest Control": easy,
  "Pharaoh's Tomb": normal,
  "The Pharaoh": hard,
  Phasmatys: hard,
  "Pheasant Peasant": hard,
  "Pick & Shovel": normal,
  "Pinball Wizard": hard,
  "Pirates of Penance": hard,
  "Pirates of Peril": normal,
  "Plots and Plans": hard,
  "Poles Apart": normal,
  "The Power of Tears": normal,
  "Power of the Shadow Realm": easy,
  "Predator Xarpus": easy,
  Preservation: easy,
  Preserved: easy,
  "Prime Time": hard,
  Principality: normal,
  "Prison Break": normal,
  Quest: hard,
  "The Quizmaster": hard,
  "Race Against the Clock": normal,
  "Rat a Tat Tat": hard,
  "Rat Hunt": hard,
  "Ready for Battle": hard,
  Regal: normal,
  "Regal Pomp": normal,
  Reggae: normal,
  "Reggae 2": normal,
  "Reign of the Basilisk": hard,
  Relics: hard,
  Rellekka: normal,
  "Rest in Peace": easy,
  Revenants: easy,
  Rhapsody: normal,
  "Right on Track": hard,
  Righteousness: hard,
  "Rising Damp": hard,
  Riverside: normal,
  "Roc and Roll": hard,
  "The Rogues' Den": hard,
  "Roll the Bones": hard,
  "Romancing the Crone": normal,
  "Romper Chomper": normal,
  "Roots and Flutes": normal,
  Rose: normal,
  Royale: hard,
  "Rugged Terrain": normal,
  "The Ruins of Camdozaal": normal,
  "Ruins of Isolation": normal,
  "Rune Essence": normal,
  "Sad Meadow": normal,
  "Safety in Numbers": hard,
  Saga: normal,
  "Sands of Time": easy,
  Sarachnis: normal,
  Sarcophagus: hard,
  "Sarim's Vermin": hard,
  "Scape Ape": hard,
  "Scape Cave": hard,
  "Scape Crystal": hard,
  "Scape Five": hard,
  "Scape Ground": hard,
  "Scape Home": hard,
  "Scape Hunter": hard,
  "Scape Main": hard,
  "Scape Original": hard,
  "Scape Sad": normal,
  "Scape Santa": hard,
  "Scape Scared": hard,
  "Scape Soft": easy,
  "Scape Wild": easy,
  "Scar Tissue": normal,
  Scarab: normal,
  "School's Out": hard,
  "Scorpia Dances": normal,
  "Scrubfoot's Descent": hard,
  "Sea Minor Shanty": hard,
  "Sea Shanty": easy,
  "Sea Shanty 2": easy,
  "Sea Shanty Xmas": hard,
  "Secrets of the North": normal,
  "The Seed of Crwys": normal,
  Serenade: normal,
  Serene: hard,
  "Servants of Strife": normal,
  Settlement: normal,
  "The Shadow": normal,
  Shadowland: normal,
  "Sharp End of the Crystal": hard,
  "Shattered Relics": hard,
  Shine: normal,
  Shining: normal,
  "Shining Spirit": normal,
  Shipwrecked: normal,
  Showdown: hard,
  "Sigmund's Showdown": hard,
  "The Sinclairs": hard,
  "The Slayer": normal,
  "Slice of Silent Movie": hard,
  "Slice of Station": hard,
  "Slither and Thither": hard,
  "Slug a Bug Ball": hard,
  "Snowflake & My Arm": normal,
  Sojourn: normal,
  "Song of the Elves": hard,
  "Song of the Silent Choir": normal,
  "Sorceress's Garden": hard,
  "Soul Fall": normal,
  "Soul Wars": normal,
  Soundscape: normal,
  Sphinx: normal,
  Spirit: easy,
  "Spirits of the Elid": hard,
  Splendour: normal,
  Spooky: easy,
  "Spooky 2": hard,
  "Spooky Jungle": normal,
  "The Spurned Demon": normal,
  "The Spymaster": hard,
  Stagnant: normal,
  "Stand Up and Be Counted": normal,
  Starlight: hard,
  Start: normal,
  "Still Night": normal,
  Stillness: hard,
  "Storeroom Shuffle": hard,
  "Storm Brew": hard,
  Stranded: normal,
  "Strange Place": hard,
  Strangled: normal,
  Stratosphere: hard,
  "Strength of Saradomin": easy,
  "Stuck in the Mire": normal,
  Subterranea: hard,
  Sunburn: normal,
  Superstition: hard,
  "Surok's Theme": normal,
  Suspicious: normal,
  "Tale of Keldagrim": hard,
  "Talking Forest": normal,
  "Tarn Razorlor": hard,
  "A Taste of Hope": normal,
  "Tears of Guthix": normal,
  Technology: hard,
  Tempest: normal,
  Temple: hard,
  "Temple of Light": hard,
  "Temple of the Eye": 366,
  "Temple of Tribes": 296,
  "Tempor of the Storm": 379,
  "The Terrible Caverns": 248,
  "The Terrible Tower": 280,
  "The Terrible Tunnels": 304,
  "Terrorbird Tussle": 324,
  "Test of Companionship": 307,
  "Test of Isolation": 259,
  "Test of Resourcefulness": 264,
  "Test of Strength": 434,
  "That Sullen Hall": 380,
  Theme: 202,
  "A Thorn in My Side": 443,
  "Thrall of the Devourer": 353,
  "Thrall of the Serpent": 351,
  "Throne of the Demon": 354,
  "Tick Tock": 116,
  "Time Out": 183,
  "Time to Mine": 287,
  Tiptoe: 281,
  "Title Fight": 184,
  "Tomb Raider": 333,
  Tomorrow: 156,
  "Too Many Cooks...": 204,
  "The Tower of Voices": 429,
  "The Tower": 175,
  "The Trade Parade": 271,
  "Trahaearn Toil": 322,
  Trawler: 260,
  "Trawler Minor": 168,
  "Tree Spirits": 240,
  Tremble: 204,
  Tribal: 127,
  "Tribal 2": 226,
  "Tribal Background": 211,
  Trinity: 216,
  "Troll Shuffle": 352,
  "Trouble Brewing": 159,
  Troubled: 225,
  "Troubled Waters": 201,
  Twilight: 311,
  "TzHaar!": 222,
  "Undead Dungeon": 197,
  Undercurrent: 324,
  Underground: 216,
  "Underground Pass": 252,
  Understanding: 237,
  "Unknown Land": 124,
  Untouchable: 194,
  "Unturned Stones": 135,
  Upcoming: 191,
  "Upir Likhyi": 367,
  "Upper Depths": 249,
  "Vampyre Assault": 190,
  Vanescula: 110,
  "The Vault": 140,
  Venomous: 213,
  Venture: 110,
  "Venture 2": 196,
  "Victory is Mine": 189,
  Village: 214,
  Vision: 170,
  "Volcanic Vikings": 202,
  "Voodoo Cult": 319,
  Voyage: 175,
  "The Waiting Game": 279,
  "Waking Dream": 196,
  "Waste Defaced": 240,
  "A Walk in the Woods": 104,
  "The Walking Dead": 234,
  "Wally the Hero": 79,
  Wander: 201,
  Warpath: 284,
  Warrior: 197,
  "Warriors' Guild": 190,
  "Watch Your Step": 382,
  Waterfall: 139,
  Waterlogged: 290,
  "Way of the Enchanter": 214,
  "Way of the Wyrm": 331,
  Wayward: 337,
  "We are the Fairies": 280,
  "Welcome to my Nightmare": 452,
  "Welcome to the Theatre": 300,
  "Well Hallowed Air": 209,
  "Well of Voyage": 194,
  "What Happens Below...": 194,
  "Where Eagles Lair": 227,
  "Wild Isle": 241,
  "Wild Side": 316,
  Wilderness: 210,
  "Wilderness 2": 180,
  "Wilderness 3": 109,
  Wildwood: 206,
  "Winter Funfair": 258,
  Witching: 93,
  "Woe of the Wyvern": 234,
  Wonder: 192,
  Wonderous: 231,
  Woodland: 202,
  "Work Work Work": 315,
  Workshop: 250,
  "A Worthy Foe": 431,
  "Wrath and Ruin": 230,
  Xenophobe: 174,
  Yesteryear: 236,
  "You Have My Attention": 399,
  "Zamorak Zoo": 181,
  "Zanik's Theme": 167,
  "Zaros Zeitgeist": 462,
  Zealot: 258,
  "Zogre Dance": 310,
  Zombiism: 228,
};
