export const songNames = [
  "7th Realm",
  "Adventure",
  "Al Kharid",
  "Alchemical Attack!",
  "All's Fairy in Love & War",
  "Alone",
  "Altar Ego",
  "Alternative Root",
  "Amascut's Promise",
  "Ambient Jungle",
  "The Ancient Prison",
  "The Angel's Fury",
  "Anywhere",
  "Ape-ex Predator",
  "Arabian",
  "Arabian 2",
  "Arabian 3",
  "Arabique",
  "Arachnids of Vampyrium",
  "Arboretum",
  "Arcane",
  "Architects of Prifddinas",
  "Armadyl Alliance",
  "Armageddon",
  "Army of Darkness",
  "Arrival",
  "Artistry",
  "Ascent",
  "Assault and Battery",
  "Attack 1",
  "Attack 2",
  "Attack 3",
  "Attack 4",
  "Attack 5",
  "Attack 6",
  "Attention",
  "Autumn Voyage",
  "Awful Anthem",
  "Aye Car Rum Ba",
  "Aztec",
  "Back to Life",
  "Background",
  "Bait",
  "Ballad of Enchantment",
  "Ballad of the Basilisk",
  "Bandit Camp",
  "Bandos Battalion",
  "Bane",
  "The Bane of Ashihama",
  "Barb Wire",
  "Barbarian Workout",
  "Barbarianism",
  "Barking Mad",
  "Baroque",
  "Barren Land",
  "Beetle Juice",
  "Beneath Cursed Sands",
  "Beneath the Kingdom",
  "Beneath the Stronghold",
  "Beyond",
  "Beyond the Meadow",
  "Big Chords",
  "Blistering Barnacles",
  "Blood Rush",
  "Bloodbath",
  "Bob's on Holiday",
  "Body Parts",
  "Bolrie's Diary",
  "Bone Dance",
  "Bone Dry",
  "Book of Spells",
  "Borderland",
  "Box of Delights",
  "Brain Battle",
  "Breeze",
  "Brew Hoo Hoo!",
  "Brimstail's Scales",
  "Bubble and Squeak",
  "Bunny's Sugar Rush",
  "Burning Desire",
  "The Burning Sun",
  "Cabin Fever",
  "Cain's Tutorial",
  "Camelot",
  "Castle Wars",
  "Catacombs and Tombs",
  "Catch Me If You Can",
  "Cave Background",
  "Cave of Beasts",
  "Cave of the Goblins",
  "Cavern",
  "The Cellar Dwellers",
  "Cellar Song",
  "Chain of Command",
  "Chamber",
  "Chef Surprise",
  "Chickened Out",
  "Children of the Sun",
  "Chompy Hunt",
  "The Chosen",
  "City of the Dead",
  "Clan Wars",
  "Clanliness",
  "Claustrophobia",
  "Close Quarters",
  "Coil",
  "Colossus of the Deep",
  "Competition",
  "Complication",
  "Confrontation",
  "The Consortium",
  "Conspiracy",
  "Contest",
  "Corporal Punishment",
  "Corridors of Power",
  "Country Jig",
  "Courage",
  "Creature Cruelty",
  "Creeping Vines",
  "Crest of a Wave",
  "Crystal Castle",
  "Crystal Cave",
  "Crystal Sword",
  "Cursed",
  "The Curtain Closes",
  "Dagannoth Dawn",
  "Dance of Death",
  "Dance of the Meilyr",
  "Dance of the Nylocas",
  "Dance of the Undead",
  "Dangerous",
  "A Dangerous Game",
  "Dangerous Road",
  "Dangerous Way",
  "Dark",
  "The Dark Beast Sotetseg",
  "Darkly Altared",
  "Darkmeyer",
  "Darkness in the Depths",
  "Davy Jones' Locker",
  "Dead Can Dance",
  "Dead Quiet",
  "Deadlands",
  "Deep Down",
  "Deep Wildy",
  "Delrith",
  "The Depths",
  "Desert Heat",
  "Desert Voyage",
  "The Desert",
  "The Desolate Isle",
  "The Desolate Mage",
  "Devils May Care",
  "Diango's Little Helpers",
  "Dies Irae",
  "Dimension X",
  "Distant Land",
  "Distillery Hilarity",
  "Dogs of War",
  "Dogfight",
  "Domain of the Vampyres",
  "Don't Panic Zanik",
  "The Doors of Dinh",
  "Doorways",
  "Dorgeshuun City",
  "Dorgeshuun Deep",
  "Dorgeshuun Treaty",
  "Dot's Yuletide",
  "Down and Out",
  "Down Below",
  "Down by the Docks",
  "Down to Earth",
  "The Dragon Slayer",
  "Dragontooth Island",
  "Dream",
  "Dreamstate",
  "The Emir's Arena",
  "Dunes of Eternity",
  "Dunjun",
  "Dusk in Yu'biusk",
  "Dwarf Theme",
  "Dwarven Domain",
  "Dynasty",
  "Eagles' Peak",
  "Easter Jig",
  "Egypt",
  "Elven Guardians",
  "Elven Mist",
  "Elven Seed",
  "Emotion",
  "Emperor",
  "The Enchanter",
  "The Enclave",
  "Escape",
  "Espionage",
  "Etceteria",
  "Eve's Epinette",
  "Everlasting",
  "Everlasting Fire",
  "The Everlasting Slumber",
  "Everywhere",
  "Evil Bob's Island",
  "Expanse",
  "Expecting",
  "Expedition",
  "Exposed",
  "Eye See You",
  "Eye of the Storm",
  "Faerie",
  "The Fairy Dragon",
  "Faith of the Hefin",
  "Faithless",
  "The Fallen Empire",
  "Fanfare",
  "Fanfare 2",
  "Fanfare 3",
  "Fangs for the Memory",
  "Far Away",
  "The Far Side",
  "A Farmer's Grind",
  "The Fat Lady Sings",
  "Fe Fi Fo Fum",
  "Fear and Loathing",
  "Fenkenstrain's Refrain",
  "A Festive Party",
  "Fight of the Basilisk",
  "Fight or Flight",
  "Find My Way",
  "Fire and Brimstone",
  "Fire in the Deep",
  "The Fires of Lletya",
  "Fishing",
  "Floating Free",
  "Flute Salad",
  "Food for Thought",
  "Forbidden",
  "Forest",
  "The Forests of Shayzien",
  "Forever",
  "Forgettable Melody",
  "Forgotten",
  "A Forgotten Religion",
  "The Forgotten Tomb",
  "The Forlorn Homestead",
  "The Forsaken Tower",
  "The Forsaken",
  "Fossilised",
  "The Foundry",
  "The Fragment",
  "The Fremennik Kings",
  "Frogland",
  "Frostbite",
  "Fruits de Mer",
  "Ful to the Brim",
  "Funny Bunnies",
  "The Galleon",
  "Gaol",
  "Garden",
  "Garden of Autumn",
  "Garden of Spring",
  "Garden of Summer",
  "Garden of Winter",
  "The Gates of Menaphos",
  "The Gauntlet",
  "The Genie",
  "Getting Down to Business",
  "Gill Bill",
  "Gnome King",
  "Gnome Village",
  "Gnome Village 2",
  "Gnome Village Party",
  "Gnomeball",
  "Goblin Game",
  "Goblin Village",
  "Golden Touch",
  "The Golem",
  "Greatness",
  "Grimly Fiendish",
  "Grip of the Talon",
  "Grotto",
  "Grow Grow Grow",
  "Grumpy",
  "Guardians of the Rift",
  "The Guardians Prepare",
  "H.A.M. and Seek",
  "H.A.M. Attack",
  "H.A.M. Fisted",
  "Harmony",
  "Harmony 2",
  "Haunted Mine",
  "Have a Blast",
  "Have an Ice Day",
  "Head to Head",
  "Healin' Feelin'",
  "Heart and Mind",
  "Hells Bells",
  "Hermit",
  "High Seas",
  "High Spirits",
  "His Faithful Servants",
  "Hoe Down",
  "Home Sweet Home",
  "Horizon",
  "The Houses of Kourend",
  "Hypnotised",
  "Iban",
  "Ice and Fire",
  "Ice Melody",
  "Illusive",
  "Impetuous",
  "Impulses",
  "In Between",
  "In the Brine",
  "In the Clink",
  "In the Manor",
  "In the Pits",
  "In the Shadows",
  "Inadequacy",
  "Incantation",
  "Inferno",
  "Insect Queen",
  "Inspiration",
  "Into the Abyss",
  "Into the Tombs",
  "Intrepid",
  "Invader",
  "Iorwerth's Lament",
  "Island Life",
  "Island of the Trolls",
  "Isle of Everywhere",
  "It's not over 'til...",
  "Itsy Bitsy...",
  "Jaws of the Basilisk",
  "Jaws of Gluttony",
  "Jester Minute",
  "Jolly R",
  "Joy of the Hunt",
  "Judgement of the Depths",
  "Jungle Bells",
  "Jungle Hunt",
  "Jungle Island",
  "Jungle Island Xmas",
  "Jungle Troubles",
  "Jungly 1",
  "Jungly 2",
  "Jungly 3",
  "Kanon of Kahlith",
  "Karamja Jam",
  "King of the Trolls",
  "Kingdom",
  "Knightly",
  "Knightmare",
  "Kourend the Magnificent",
  "La Mort",
  "Labyrinth",
  "Lagoon",
  "Laid to Rest",
  "Lair",
  "Lair of the Basilisk",
  "Lament",
  "Lament for the Hallowed",
  "Lament of Meiyerditch",
  "Land Down Under",
  "Land of Snow",
  "Land of the Dwarves",
  "Landlubber",
  "Last King of the Yarasa",
  "Last Man Standing",
  "The Last Shanty",
  "Last Stand",
  "Lasting",
  "Lava is Mine",
  "Legend",
  "Legion",
  "Life's a Beach!",
  "Lighthouse",
  "Lightness",
  "Lightwalk",
  "Little Cave of Horrors",
  "Lonesome",
  "Long Ago",
  "Long Way Home",
  "The Longramble Scramble",
  "Look to the Stars",
  "Looking Back",
  "Lore and Order",
  "The Lost Melody",
  "Lost Soul",
  "The Lost Tribe",
  "Lower Depths",
  "Lucid Dream",
  "Lucid Nightmare",
  "Lullaby",
  "Lumbering",
  "The Lunar Isle",
  "Mad Eadgar",
  "The Mad Mole",
  "Mage Arena",
  "Magic Dance",
  "Magic Magic Magic",
  "Magical Journey",
  "The Maiden's Anger",
  "The Maiden's Sorrow",
  "Major Miner",
  "Making Waves",
  "Malady",
  "March",
  "March of the Shayzien",
  "Marooned",
  "Marzipan",
  "Masquerade",
  "Master of Puppets",
  "Mastermindless",
  "Mausoleum",
  "Maws Jaws & Claws",
  "The Maze",
  "Meddling Kids",
  "Medieval",
  "Mellow",
  "Melodrama",
  "Meridian",
  "Method of Madness",
  "Miles Away",
  "Military Life",
  "The Militia",
  "Mind over Matter",
  "Miracle Dance",
  "Mirage",
  "Miscellania",
  "The Mollusc Menace",
  "Monarch Waltz",
  "Monkey Badness",
  "Monkey Business",
  "Monkey Madness",
  "Monkey Sadness",
  "Monkey Trouble",
  "Monster Melee",
  "The Monsters Below",
  "Moody",
  "Mor Ul Rek",
  "More Than Meets the Eye",
  "Morytania",
  "Morytanian Mystery",
  "A Mother's Curse",
  "Mother Ruckus",
  "Mouse Trap",
  "Mudskipper Melody",
  "Museum Medley",
  "Mutant Medley",
  "My Arm's Journey",
  "Mystics of Nature",
  "Mythical",
  "Narnode's Theme",
  "Natural",
  "The Navigator",
  "Nether Realm",
  "Neverland",
  "Newbie Farming",
  "Newbie Melody",
  "Night of the Vampyre",
  "Nightfall",
  "The Nightmare Continues",
  "No Pasaran",
  "No Way Out",
  "The Noble Rodent",
  "Nomad",
  "Norse Code",
  "Not a Moment of Relief",
  "Nox Irae",
  "Null and Void",
  "Ogre the Top",
  "Oh Rats!",
  "The Old Ones",
  "On the Frontline",
  "On the Shore",
  "On the Up",
  "On the Wing",
  "On Thin Ice",
  "Oncoming Foe",
  "Organ Music 1",
  "Organ Music 2",
  "Oriental",
  "The Other Side",
  "Out at the Mines",
  "Out of the Deep",
  "Over to Nardah",
  "Overpass",
  "Overture",
  "Parade",
  "The Part Where You Die",
  "Path of Peril",
  "The Penguin Bards",
  "Penguin Plots",
  "Pathways",
  "Pest Control",
  "Pharaoh's Tomb",
  "The Pharaoh",
  "Phasmatys",
  "Pheasant Peasant",
  "Pick & Shovel",
  "Pinball Wizard",
  "Pirates of Penance",
  "Pirates of Peril",
  "Plots and Plans",
  "Poles Apart",
  "The Power of Tears",
  "Power of the Shadow Realm",
  "Predator Xarpus",
  "Preservation",
  "Preserved",
  "Prime Time",
  "Principality",
  "Prison Break",
  "Quest",
  "The Quizmaster",
  "Race Against the Clock",
  "Rat a Tat Tat",
  "Rat Hunt",
  "Ready for Battle",
  "Regal",
  "Regal Pomp",
  "Reggae",
  "Reggae 2",
  "Reign of the Basilisk",
  "Relics",
  "Rellekka",
  "Rest in Peace",
  "Revenants",
  "Rhapsody",
  "Right on Track",
  "Righteousness",
  "Rising Damp",
  "Riverside",
  "Roc and Roll",
  "The Rogues' Den",
  "Roll the Bones",
  "Romancing the Crone",
  "Romper Chomper",
  "Roots and Flutes",
  "Rose",
  "Royale",
  "Rugged Terrain",
  "The Ruins of Camdozaal",
  "Ruins of Isolation",
  "Rune Essence",
  "Sad Meadow",
  "Safety in Numbers",
  "Saga",
  "Sands of Time",
  "Sarachnis",
  "Sarcophagus",
  "Sarim's Vermin",
  "Scape Ape",
  "Scape Cave",
  "Scape Crystal",
  "Scape Five",
  "Scape Ground",
  "Scape Home",
  "Scape Hunter",
  "Scape Main",
  "Scape Original",
  "Scape Sad",
  "Scape Santa",
  "Scape Scared",
  "Scape Soft",
  "Scape Wild",
  "Scar Tissue",
  "Scarab",
  "School's Out",
  "Scorpia Dances",
  "Scrubfoot's Descent",
  "Sea Minor Shanty",
  "Sea Shanty",
  "Sea Shanty 2",
  "Sea Shanty Xmas",
  "Secrets of the North",
  "The Seed of Crwys",
  "Serenade",
  "Serene",
  "Servants of Strife",
  "Settlement",
  "The Shadow",
  "Shadowland",
  "Sharp End of the Crystal",
  "Shattered Relics",
  "Shine",
  "Shining",
  "Shining Spirit",
  "Shipwrecked",
  "Showdown",
  "Sigmund's Showdown",
  "The Sinclairs",
  "The Slayer",
  "Slice of Silent Movie",
  "Slice of Station",
  "Slither and Thither",
  "Slug a Bug Ball",
  "Snowflake & My Arm",
  "Sojourn",
  "Song of the Elves",
  "Song of the Silent Choir",
  "Sorceress's Garden",
  "Soul Fall",
  "Soul Wars",
  "Soundscape",
  "Sphinx",
  "Spirit",
  "Spirits of the Elid",
  "Splendour",
  "Spooky",
  "Spooky 2",
  "Spooky Jungle",
  "The Spurned Demon",
  "The Spymaster",
  "Stagnant",
  "Stand Up and Be Counted",
  "Starlight",
  "Start",
  "Still Night",
  "Stillness",
  "Storeroom Shuffle",
  "Storm Brew",
  "Stranded",
  "Strange Place",
  "Strangled",
  "Stratosphere",
  "Strength of Saradomin",
  "Stuck in the Mire",
  "Subterranea",
  "Sunburn",
  "Superstition",
  "Surok's Theme",
  "Suspicious",
  "Tale of Keldagrim",
  "Talking Forest",
  "Tarn Razorlor",
  "A Taste of Hope",
  "Tears of Guthix",
  "Technology",
  "Tempest",
  "Temple",
  "Temple of Light",
  "Temple of the Eye",
  "Temple of Tribes",
  "Tempor of the Storm",
  "The Terrible Caverns",
  "The Terrible Tower",
  "The Terrible Tunnels",
  "Terrorbird Tussle",
  "Test of Companionship",
  "Test of Isolation",
  "Test of Resourcefulness",
  "Test of Strength",
  "That Sullen Hall",
  "Theme",
  "A Thorn in My Side",
  "Thrall of the Devourer",
  "Thrall of the Serpent",
  "Throne of the Demon",
  "Tick Tock",
  "Time Out",
  "Time to Mine",
  "Tiptoe",
  "Title Fight",
  "Tomb Raider",
  "Tomorrow",
  "Too Many Cooks...",
  "The Tower of Voices",
  "The Tower",
  "The Trade Parade",
  "Trahaearn Toil",
  "Trawler",
  "Trawler Minor",
  "Tree Spirits",
  "Tremble",
  "Tribal",
  "Tribal 2",
  "Tribal Background",
  "Trinity",
  "Troll Shuffle",
  "Trouble Brewing",
  "Troubled",
  "Troubled Waters",
  "Twilight",
  "TzHaar!",
  "Undead Dungeon",
  "Undercurrent",
  "Underground",
  "Underground Pass",
  "Understanding",
  "Unknown Land",
  "Untouchable",
  "Unturned Stones",
  "Upcoming",
  "Upir Likhyi",
  "Upper Depths",
  "Vampyre Assault",
  "Vanescula",
  "The Vault",
  "Venomous",
  "Venture",
  "Venture 2",
  "Victory is Mine",
  "Village",
  "Vision",
  "Volcanic Vikings",
  "Voodoo Cult",
  "Voyage",
  "The Waiting Game",
  "Waking Dream",
  "Waste Defaced",
  "A Walk in the Woods",
  "The Walking Dead",
  "Wally the Hero",
  "Wander",
  "Warpath",
  "Warrior",
  "Warriors' Guild",
  "Watch Your Step",
  "Waterfall",
  "Waterlogged",
  "Way of the Enchanter",
  "Way of the Wyrm",
  "Wayward",
  "We are the Fairies",
  "Welcome to my Nightmare",
  "Welcome to the Theatre",
  "Well Hallowed Air",
  "Well of Voyage",
  "What Happens Below...",
  "Where Eagles Lair",
  "Wild Isle",
  "Wild Side",
  "Wilderness",
  "Wilderness 2",
  "Wilderness 3",
  "Wildwood",
  "Winter Funfair",
  "Witching",
  "Woe of the Wyvern",
  "Wonder",
  "Wonderous",
  "Woodland",
  "Work Work Work",
  "Workshop",
  "A Worthy Foe",
  "Wrath and Ruin",
  "Xenophobe",
  "Yesteryear",
  "You Have My Attention",
  "Zamorak Zoo",
  "Zanik's Theme",
  "Zaros Zeitgeist",
  "Zealot",
  "Zogre Dance",
  "Zombiism",
] as const;

export type SongName = (typeof songNames)[number];
