name: AutomaticHost

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile
      - run: yarn run build
        working-directory: ./shared
      - run: yarn run build
        working-directory: ./client
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git reset
          git add client/dist/* -f
          git mv client/dist/* ./ -k
          touch .nojekyll
          git add .nojekyll
          git commit -m "Update hosted version"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: gh-pages
